[package]
name = "protos"
version = "0.1.0"
authors = ["robertking <superobertking@icloud.com>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
protoc-grpcio = "0.3.1"

[dependencies]
futures = "0.1"
grpcio = "0.4"
protobuf = "2"
